version: '3.9'

services:
  deutsch_deck_webapi:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - /app/obj
      - /app/bin 
    env_file:
      - .env